# Generated by Django 4.2.1 on 2023-05-21 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=64, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='food',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='menu_img', verbose_name='фото'),
        ),
    ]
