# Generated by Django 4.2.1 on 2023-05-21 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_alter_food_name_alter_food_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='slug',
            field=models.SlugField(default=0, max_length=64, verbose_name='Slug'),
            preserve_default=False,
        ),
    ]
