# Generated by Django 4.2.1 on 2023-05-22 00:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_category_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='price',
        ),
    ]
